package dnf_InterfacesAndExceptions;

public enum AddOn
{
	NONE, CRITICAL, STAT, ATK, ACCESSORY, AIDEQUIPMENT, MAGICSTONE, RED, GREEN, YELLOW, BLUE,
	ROBE, WEAPON, TITLE, RED_GREEN, YELLOW_BLUE, MULTIPLE_COLOR
}
