package dnf_InterfacesAndExceptions;

public interface InterfaceSize {
	int INFO_BUTTON_SIZE=42;
	int SKILL_BUTTON_SIZE=30;
	
	int USER_INFO_INTERVAL=5;
	int USER_INFO_ITEM_SIZE_X=360; int USER_INFO_ITEM_SIZE_Y=180;
	int USER_STAT_MODE_SIZE_X=360; int USER_STAT_MODE_SIZE_Y=30;
	int USER_INFO_STAT_SIZE_X=360; int USER_INFO_STAT_SIZE_Y=180;
	int USER_INFO_NONSTAT_SIZE_X=380; int USER_INFO_NONSTAT_SIZE_Y=USER_INFO_ITEM_SIZE_Y+USER_INFO_INTERVAL+USER_STAT_MODE_SIZE_Y+USER_INFO_INTERVAL+USER_INFO_STAT_SIZE_Y+8;
	int USER_INFO_NONSTAT_SIZE_INDUNGEON_X = 340;	int USER_INFO_NONSTAT_SIZE_INDUNGEON_Y = 300;
	int VAULT_SIZE_Y=USER_INFO_NONSTAT_SIZE_Y+40;
	
	int CHARACTER_IMAGE_X=140; int CHARACTER_IMAGE_Y=140;
	
	int ITEM_INFO_SIZE=250;
	int SET_INFO_SIZE=250; int SET_ITEM_INTERVAL=5;
	int SKILL_INFO_SIZE=300;
	int MONSTER_INFO_SIZE=250;
	
	int DEALCHART_DEALSIZE_X=220; int DEALCHART_HPSIZE_X=100;
	int DEALCHART_Y=580;
	
	int TRAININGROOM_SIZE_X=800; int TRAININGROOM_SIZE_Y=400;
	int MONSTER_SIZE_X=300; int MONSTER_SIZE_Y=380;
	int SUB_MONSTER_SIZE_X=42; int  SUB_MONSTER_SIZE_Y=42;
	int PARTY_SIZE_X=140, PARTY_SIZE_Y=140;
	int TRAININGROOM_SETTING_SIZE_X = 490; int TRAININGROOM_SETTING_SIZE_Y = 220;
	
	int MARGIN=5;
}
