package dnf_InterfacesAndExceptions;

public enum SetName
{
	NONE,
	DARKGOTH, CHAMELEON, SUBMARINE, DARKHOLE, INFINITY,
	BURNINGSPELL, DROPPER, TACTICAL, ASSASSIN, NATURALGARDIAN,
	EYESHIELD, SPIDERQUEEN, FORBIDDENCONTRACT, MAELSTORM, FULLPLATE,
	SUPERSTAR, REFINEDSPELL, ICEQUEEN, HUGEFORM,
	GREATGLORY, GRACIA, DEVASTEDGRIEF, BURIEDSCREAM, ROOTOFDISEASE, ROMANTICE, CURSEOFSEAGOD,
	RELIC
}